version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    networks:
      - app-network
    restart: always
    command: npm run start:worker
    environment:
      - NODE_ENV=development

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:

volumes:
  mongo-data:
