# Use Node.js 20.9.0 as base image
FROM node:20.9.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --omit=dev

# Copy the rest of the application files
COPY . .

# **Build the project**
RUN npm run build

# Define environment variables
ENV NODE_ENV=production

# **Run the Worker**
CMD ["node", "-r", "tsconfig-paths/register", "dist/infrastructure/workers/taskWorker.js"]
